services:
    web_chat_app:
        build:
            context: .
            dockerfile: ./docker/php.dockerfile
        container_name: web_chat_app
        restart: unless-stopped
        volumes:
            - .:/var/www
        networks:
            - web_chat_app_network
        depends_on:
            - postgres
        ports:
            - "8080:8080"
    postgres:
        image: postgres
        container_name: web_chat_postgres
        restart: unless-stopped
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - web_chat_app_network
        ports:
            -   "5435:5435"  
    pgadmin:
        image: dpage/pgadmin4
        container_name: chat_pgadmin
        restart: unless-stopped
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
        ports:
            - "8081:80"
        networks:
            - web_chat_app_network
    nginx:
        container_name: chat_nginx
        image: nginx:alpine  # Use the Nginx image
        ports:
            - "9000:80"  # Map port 8080 on the host to port 80 inside the container
        volumes:
            - ./:/var/www  # Mount the Laravel web_chat_application directory-
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf  # Use our Nginx config
        depends_on:
            - web_chat_app  # Ensure PHP-FPM is started before Nginx
        networks:
            - web_chat_app_network  # Connect to the custom network
    node:
        image: node:22
        container_name: chat_node
        working_dir: /var/www
        volumes:
            - ./:/var/www
        tty: true
        ports:
            - "5175:5175"  # For Vite development server
        environment:
            - NODE_ENV=development
        command: >
            sh -c "npm install && npm run dev"
        networks:
            - web_chat_app_network
    redis:
        image: redis:latest
        container_name: websocket_redis
        ports:
            - "6375:6375"
        volumes:
            - redis-data:/data
        networks:
            - web_chat_app_network
volumes:
    postgres_data:
    redis-data:
networks:
    web_chat_app_network:
        driver: bridge